import dotenv from 'dotenv';
dotenv.config();

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Sends a production-grade Rich Embed to Discord.
 * Implements exponential backoff and rate-limit handling to guarantee delivery.
 * 
 * @param {Object} setup The top setup object generated by scannerEngine
 * @param {number} retries Current retry attempt count
 */
export async function sendDiscordSignal(setup, retries = 0) {
    const webhookUrl = process.env.DISCORD_API;
    
    if (!webhookUrl) {
        console.warn('[DISCORD ENGINE] WARNING: DISCORD_API not set in .env. Skipping signal dispatch.');
        return false;
    }

    // Color Coding: Green for UP/BULLISH, Red for DOWN/BEARISH
    let embedColor = 16777215; // White default
    if (setup.microRegime === 'UP' || setup.macroRegime === 'TRENDING') embedColor = 5763719; // Green
    if (setup.microRegime === 'DOWN' || setup.flowBias === 'STRONG_SELL') embedColor = 15548997; // Red

    // Construct the Institutional Rich Embed
    const payload = {
        username: "GhostTrade Quant Engine",
        avatar_url: "https://i.imgur.com/Affb7X2.png", // Replace with actual logo URL if available
        embeds: [
            {
                title: `🚨 GHOST SIGNAL: ${setup.ticker} 🚨`,
                description: "The Quant Engine has identified a high-probability asymmetric setup.",
                color: embedColor,
                fields: [
                    {
                        name: "📊 Quant Score & Edge",
                        value: `**Score:** ${setup.score}/100\n**Net EV:** ${setup.evNet}%\n**Kelly Sizing:** ${setup.recommendedSize.toFixed(1)}% of Capital`,
                        inline: false
                    },
                    {
                        name: "🔬 Regime & Order Flow",
                        value: `**Macro:** ${setup.macroRegime}\n**Micro:** ${setup.microRegime}\n**Live Flow:** ${setup.flowBias}`,
                        inline: true
                    },
                    {
                        name: "🛡️ Institutional Risk Armor",
                        value: `**Win Rate:** ${setup.expectancy.winRate}\n**3x Loss Risk:** ${setup.expectancy.lossStreak3xChance}\n**Invalidation (Stop):** $${setup.invalidationPrice}`,
                        inline: true
                    },
                    {
                        name: "⏱️ Execution Window",
                        value: `**Valid Until:** \n<t:${Math.floor(new Date(setup.validUntil).getTime() / 1000)}:R>`,
                        inline: false
                    }
                ],
                footer: {
                    text: "GhostTrade Engine v2.0 • Zero-BS Mathematics"
                },
                timestamp: new Date().toISOString()
            }
        ]
    };

    try {
        const response = await fetch(webhookUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (response.ok) {
            console.log(`[DISCORD ENGINE] ✅ Successfully dispatched signal for ${setup.ticker}`);
            return true;
        }

        // Handle Rate Limiting (HTTP 429)
        if (response.status === 429) {
            const retryAfter = response.headers.get('Retry-After') || 2;
            console.warn(`[DISCORD ENGINE] ⚠️ Rate limited. Retrying after ${retryAfter}s...`);
            await sleep(retryAfter * 1000);
            return sendDiscordSignal(setup, retries + 1);
        }

        console.error(`[DISCORD ENGINE] ❌ Failed to dispatch signal. Status: ${response.status}`);
        return false;
    } catch (error) {
        if (retries < 3) {
            const backoff = Math.pow(2, retries) * 1000;
            console.warn(`[DISCORD ENGINE] ⚠️ Network error (${error.message}). Retrying in ${backoff/1000}s...`);
            await sleep(backoff);
            return sendDiscordSignal(setup, retries + 1);
        }
        console.error(`[DISCORD ENGINE] ❌ Critical failure sending signal after 3 retries:`, error.message);
        return false;
    }
}
