import React from 'react';
import { useNavigate } from 'react-router-dom';
import { PublicLayout } from './ui/SignInFlow';
import { ChevronLeft, Terminal, ShieldAlert, FileText, Settings, Activity, Scale } from 'lucide-react';
import { motion } from 'framer-motion';
import './FooterPages.css';

// =====================================
// 1. DEDICATED LEGAL & COMPLIANCE PAGES
// =====================================

export const TermsOfServicePage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Scale size={32} className="header-icon" />
            <h1>Terms of Service</h1>
            <div className="last-updated">Last Updated: {new Date().toLocaleDateString()}</div>
          </div>
          <div className="document-content">
            <h3>1. ACCEPTANCE OF TERMS</h3>
            <p>By accessing Ghostrade, you agree to these Terms of Service. Ghostrade is an AI-powered market analysis platform designed for educational and informational purposes only. It is NOT a trading platform, broker-dealer, investment advisory service, or SEBI-registered entity.</p>
            <h3>2. NATURE OF SERVICE</h3>
            <p>Ghostrade provides AI-generated quantitative analysis, technical indicator computations, and data visualization tools. All outputs are mathematical observations derived from publicly available market data. Nothing on this platform constitutes investment advice, trading recommendations, or personalized financial guidance.</p>
            <h3>3. NO INVESTMENT ADVICE</h3>
            <p>Ghostrade does not recommend, advise, or suggest any investment action. All analysis is generated by AI models and should be treated as educational content only. Users must consult a SEBI-registered Investment Adviser before making any investment decisions.</p>
            <h3>4. USER RESPONSIBILITY</h3>
            <p>Users are solely responsible for their own investment decisions. Ghostrade shall not be liable for any financial losses arising from the use of analysis provided on this platform. Investment in securities market is subject to market risks.</p>
            <h3>5. SIMULATED TRADING</h3>
            <p>Any paper trading or simulated execution features on this platform use virtual/simulated funds only. These features are for educational learning purposes and do not involve real money or real market orders.</p>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

export const PrivacyPolicyPage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Scale size={32} className="header-icon" />
            <h1>Privacy Policy</h1>
            <div className="last-updated">Last Updated: {new Date().toLocaleDateString()}</div>
          </div>
          <div className="document-content">
            <h3>1. DATA COLLECTION</h3>
            <p>We collect usage analytics, session data, and analysis request logs to improve our AI models. We do not collect or store any financial account credentials, brokerage passwords, or payment information on our servers.</p>
            <h3>2. DATA USAGE</h3>
            <p>Your analysis requests and interaction data are used solely to improve the quality of our AI-generated analysis. We do not sell, share, or distribute your personal data to third parties for marketing purposes.</p>
            <h3>3. DATA RETENTION</h3>
            <p>Session and analysis data is retained for service improvement purposes. Users may request deletion of their data by contacting our support team.</p>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

export const RiskDisclosurePage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Scale size={32} className="header-icon" />
            <h1>Risk Disclosure</h1>
            <div className="last-updated">Last Updated: {new Date().toLocaleDateString()}</div>
          </div>
          <div className="document-content">
            <h3>⚠️ IMPORTANT RISK WARNING</h3>
            <p><strong>Investment in securities market is subject to market risks. Read all the related documents carefully before investing.</strong></p>
            <h3>AI ANALYSIS LIMITATIONS</h3>
            <p>Ghostrade uses artificial intelligence to generate quantitative market analysis. AI models are probabilistic and can produce inaccurate or misleading results. No AI system can predict market movements with certainty. Past analytical accuracy does not guarantee future performance.</p>
            <h3>NOT INVESTMENT ADVICE</h3>
            <p>Ghostrade is not registered with the Securities and Exchange Board of India (SEBI) as an Investment Adviser (under IA Regulations, 2013) or Research Analyst (under RA Regulations, 2014). All content on this platform is for educational and informational purposes only and does not constitute investment advice, research reports, or trade recommendations.</p>
            <h3>USER ACKNOWLEDGMENT</h3>
            <p>By using Ghostrade, you acknowledge that: (a) you understand AI-generated analysis may be inaccurate, (b) you will not treat any output as investment advice, (c) you will consult a SEBI-registered professional before making investment decisions, and (d) you assume full responsibility for your own financial decisions.</p>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

export const MasterServiceAgreementPage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Scale size={32} className="header-icon" />
            <h1>Master Service Agreement</h1>
            <div className="last-updated">Last Updated: {new Date().toLocaleDateString()}</div>
          </div>
          <div className="document-content">
            <h3>SERVICE DESCRIPTION</h3>
            <p>Ghostrade provides an AI-powered market analysis platform accessible via web interface. The service includes quantitative analysis generation, technical indicator computation, and educational content delivery.</p>
            <h3>SERVICE AVAILABILITY</h3>
            <p>We strive to maintain high availability but do not guarantee uninterrupted access. The service may experience downtime for maintenance, updates, or due to third-party API dependencies. No compensation is provided for service interruptions.</p>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

// =====================================
// 2. PLATFORM PAGES
// =====================================

export const ApiDocsPage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Terminal size={32} className="header-icon" />
            <h1>API Documentation</h1>
            <p>Connect to the Ghostrade analysis engine via WebSocket for real-time market data streaming.</p>
          </div>
          
          <div className="api-code-block">
            <pre>
{`// Initialize WebSocket Connection
const ws = new WebSocket('wss://api.ghostrade.com/v1/stream');

ws.onopen = () => {
  ws.send(JSON.stringify({
    action: "subscribe",
    channels: ["orderbook.L2", "execution.fills"],
    auth_token: "YOUR_API_KEY"
  }));
};`}
            </pre>
          </div>
          
          <div className="document-content mt-4">
            <h3>Endpoints</h3>
            <ul>
              <li><code>WS /v1/stream</code> — Real-time analysis stream</li>
              <li><code>GET /v1/analysis</code> — Fetch analysis results</li>
              <li><code>GET /v1/indicators</code> — Technical indicator data</li>
            </ul>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

export const BrokerIntegrationsPage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Settings size={32} className="header-icon" />
            <h1>Data Connections</h1>
            <p>Market data sources powering Ghostrade analysis.</p>
          </div>
          
          <div className="integration-grid">
            <div className="integration-card">
              <h3>Binance Institutional</h3>
              <p>Market data WebSocket stream for crypto analysis.</p>
              <div className="status-badge connected">Supported</div>
            </div>
            <div className="integration-card">
              <h3>Interactive Brokers</h3>
              <p>Global equity and options market data API.</p>
              <div className="status-badge connected">Supported</div>
            </div>
            <div className="integration-card">
              <h3>Deribit</h3>
              <p>Derivatives market data websocket integration.</p>
              <div className="status-badge connected">Supported</div>
            </div>
            <div className="integration-card">
              <h3>Coinbase Prime</h3>
              <p>Institutional market data feeds.</p>
              <div className="status-badge pending">Beta Access</div>
            </div>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

export const StatusDashboardPage = () => {
  const navigate = useNavigate();
  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          <div className="page-header">
            <Activity size={32} className="header-icon" />
            <h1>System Status</h1>
            <p>Real-time telemetry and infrastructure health.</p>
          </div>
          
          <div className="status-banner operational">
            All Systems Operational
          </div>
          
          <div className="status-metrics">
            <div className="status-row">
              <span>Analysis Engine</span>
              <span className="metric-good">Operational</span>
            </div>
            <div className="status-row">
              <span>WebSocket Stream</span>
              <span className="metric-good">Active</span>
            </div>
            <div className="status-row">
              <span>Signal Audit Log</span>
              <span className="metric-good">Operational</span>
            </div>
            <div className="status-row">
              <span>AI Model Inference</span>
              <span className="metric-good">Operational</span>
            </div>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

// =====================================
// 3. ARCHITECTURE PAGES
// =====================================

export const ArchitecturePage = ({ title, type }) => {
  const navigate = useNavigate();
  
  const getContent = () => {
    switch (type) {
      case 'oracle':
        return (
          <>
            <h3>AI ORACLE ENGINE</h3>
            <p>The Analysis Engine uses advanced AI models (powered by Google Gemini) to process real-time market data including OHLCV candles, technical indicators, order flow metrics, and regime classification to generate quantitative analysis.</p>
            <h3>PREDICTIVE MODELING</h3>
            <p>Utilizing advanced deep learning networks (transformers and LSTMs), the Oracle generates probabilistic vectors for asset movements over multiple time horizons (tick-level to multi-day).</p>
            <h3>CONTINUOUS LEARNING</h3>
            <p>The model autonomously recalibrates its weights based on the outcomes of its own cryptographic audit ledger, ensuring adaptation to shifting market regimes without human intervention.</p>
          </>
        );
      case 'router':
        return (
          <>
            <h3>DATA PIPELINE</h3>
            <p>Data freshness is critical. Our Data Pipeline fetches data from market APIs and streams it via WebSockets directly to clients.</p>
            <h3>MARKET DATA INTEGRATION</h3>
            <p>The pipeline actively processes large volumes of market data and distributes it across analysis components to ensure high quality signals.</p>
            <h3>SUB-MILLISECOND LATENCY</h3>
            <p>Housed in cloud servers, the pipeline achieves processing latencies measured in microseconds.</p>
          </>
        );
      case 'risk':
        return (
          <>
            <h3>RISK SENTINEL</h3>
            <p>The Risk Sentinel operates as a completely independent sub-system from the Oracle Engine. Its sole purpose is to monitor portfolio exposure, margin utilization, and systemic risk.</p>
            <h3>DYNAMIC HEDGING</h3>
            <p>When the Sentinel detects beta exposure exceeding institutional thresholds, it automatically routes inverse delta-neutral hedging orders to counteract the risk.</p>
            <h3>HARD STOPS & CIRCUIT BREAKERS</h3>
            <p>In the event of a flash crash or extreme market volatility, the Risk Sentinel engages hard cryptographic circuit breakers, pausing analysis when data quality is insufficient.</p>
          </>
        );
      case 'ledger':
        return (
          <>
            <h3>VERIFIED LEDGER</h3>
            <p>Trust is mathematical. The Verified Ledger is an immutable log of every single signal and analysis generated by the system.</p>
            <h3>COMPLIANCE TRACKING</h3>
            <p>A MongoDB-based signal tracking system logs all system actions and potential compliance violations for auditing purposes.</p>
            <h3>REAL-TIME AUDITABILITY</h3>
            <p>Clients can verify that the historical performance metrics displayed on the dashboard match the actual data recorded on the ledger.</p>
          </>
        );
      default:
        return <p>Architecture document unavailable.</p>;
    }
  };

  return (
    <PublicLayout>
      <div className="footer-page-wrapper">
        <div className="footer-page-container">
          <button className="back-button" onClick={() => navigate(-1)}><ChevronLeft size={18} /> Back</button>
          
          <div className="page-header">
            <ShieldAlert size={32} className="header-icon" />
            <h1>{title}</h1>
            <p>Core Infrastructure Specification</p>
          </div>
          
          <div className="document-content">
            {getContent()}
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};
